# This Repository contains all the files that are related to my 4-Week internship as a AI & Cloud intern at IBM Edunet provided in association with AICTE. The attached files and Pdfs contains all the source files of the project.


## My Project ->> AI-Powered LaTeX Diagram Generator for Academic Research.  
     Create TikZ diagrams from plain English or sketches—instantly!  


## PROBLEM STATEMENT

Academic researchers and writers often struggle when creating diagrams in LaTeX, particularly using the TikZ package. Manually writing TikZ code is not only time-consuming but demands a high level of technical proficiency and is vulnerable to coding errors. This complexity leads to delays in documentation, poses a steep learning curve for newcomers, and detracts from overall productivity. There is a pressing need for a smart and accessible solution that simplifies and streamlines this process. 

## PROPOSED SOLUTION

To address this challenge, I propose an AI-powered intelligent assistant designed to automatically generate TikZ diagrams from natural language descriptions and rough sketches. This system offers real-time feedback, allows users to make refinements using plain English commands, and produces publication-ready LaTeX graphics. By eliminating manual coding, it significantly enhances the efficiency and accessibility of academic documentation—empowering researchers with fast, intuitive, and high-quality diagram creation.

## TECHNOLOGY USED

IBM cloud lite services  
Natural Language Processing (NLP)  
Retrieval Augmented Generation (RAG)  
IBM Granite model  

## IBM CLOUD SERVICES USED

IBM Cloud Watsonx AI Studio  
IBM Cloud Watsonx AI runtime  
IBM Cloud service   
IBM Granite (via watsonx.ai studio)  
IBM Cloud Object Storage IBM AI Tools  

## 🚀 Prerequisites**

To use or replicate this project, follow these step-by-step instructions:

## Step 1: Create an IBM Cloud Account
- Sign up or log in at [cloud.ibm.com](https://cloud.ibm.com)
- **Note:** If you don't have a premium account, the **Lite version** of IBM Cloud will work perfectly for this project

## Step 2: Navigate to Agent Lab (Beta)
1. Open the **Navigation Menu** on the left side of your dashboard  
2. Navigate to: `watsonx` → `watsonx.ai` → `Gen AI Solutions`  
3. Click on **"Automating Tasks with AI Agents"**  
4. Scroll down and select **"Agent Lab (beta)"**

## Step 3: Access watsonx.ai Studio
- In the Agent Lab (beta) page, click on the **"watsonx.ai Home Page"** link  
- Launch the **watsonx.ai Studio**

## Step 4: Create a Sandbox Project
- Inside the studio, click **"Create Project"**  
- Select the **"Sandbox"** option

## Step 5: Build Your AI Agent
Navigate to the **"Build AI Agent"** section and provide the following details:

| Field               | Input                                          |
|---------------------|------------------------------------------------|
| **Agent Name**      | Your preferred agent name                      |
| **Description**     | Brief description of your LaTeX diagram generator |
| **Instructions**    | Detailed instructions for TikZ diagram generation |
| **Foundation Model**| `IBM Granite-3.3-8B instruct`                  |
| **Tools**           | Select necessary tools (compatible with Lite version) |

## 🎉 You're All Set!
Your AI agent is now ready for testing and deployment.

---

> **💡 Pro Tip:** Make sure to save your project settings before proceeding to the testing phase.



## RESULTS (Screenshots of working AI Agent)

Here is the agent preview

![App Screenshot](https://res.cloudinary.com/ds8fnrk7s/image/upload/v1754386021/Screenshot_2025-08-05_134112_omnzwk.png)

Question 1 : Draw a labeled free-body diagram of a block on an inclined plane.

![App Screenshot](https://res.cloudinary.com/ds8fnrk7s/image/upload/v1754386021/Screenshot_2025-08-05_133532_nbqmzz.png)

Question 2 : Make a UML class diagram with classes: Car, ElectricCar, and Engine. 

![App Screenshot](https://res.cloudinary.com/ds8fnrk7s/image/upload/v1754386021/Screenshot_2025-08-05_133507_aawzn3.png)

![App Screenshot](https://github.com/Adityasen-cmd/Edunet_Internship_2025/blob/main/Screenshots%20of%20project/Result%203%20TikZ.png?raw=true)


## Deployment

To deploy this project

```bash
  Go to the Deploy option above(top right corner) in watsonx.ai studio and deploy it.
```
Below is the image of the deployment 

![App Screenshot](https://res.cloudinary.com/ds8fnrk7s/image/upload/v1754386021/Screenshot_2025-08-05_141351_ynzvqo.png)


## TikZ Code to Diagram generation 

Register or sign in on the "Overleaf" website.

Copy the TikZ code which is generated by Agent and paste it here.
It will show like this..  

![App Screenshot](https://res.cloudinary.com/ds8fnrk7s/image/upload/v1754386366/Screenshot_2025-08-05_135927_yodpcr.png)

## Conclusion

Simplifies Complex Tasks: Automatically generates LaTeX TikZ diagrams from natural language or sketch inputs, removing the need for manual coding.

Increases Research Efficiency: Helps researchers, students, and educators save valuable time by streamlining the creation of accurate, high-quality diagrams.

Improves Accessibility: Enables users without technical expertise to create professional diagrams easily with intuitive commands and instant feedback.

## Future scope

**Voice-Controlled Diagram Generation** Enable hands-free interaction through speech-to-text input, enhancing accessibility and speeding up the design process.
**Multilingual Command Support** Accept natural language inputs in multiple languages, empowering researchers worldwide to work in their preferred linguistic environment.
**Seamless Overleaf Integration** Embed real-time TikZ diagram rendering and editing directly into Overleaf for streamlined LaTeX workflow management.
**Context-Aware Diagram Suggestions** Automatically recommend suitable diagrams based on adjacent LaTeX content and semantic analysis of the document.
**Real-Time Collaborative Editing** Facilitate simultaneous editing by multiple users, making it ideal for team-based research and co-authoring scenarios.
**AI-Guided Layout Optimization** Provide intelligent layout suggestions to improve clarity, aesthetics, and readability of complex diagrams.
**Multi-Format Export Capability Support** exports in TikZ, PNG, SVG, and PDF formats for flexible use across publications, presentations, and teaching materials.



## License

[MIT](https://choosealicense.com/licenses/mit/)

Copyright (c) 2025 Mani Prasoon Miryala

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 
